# Rename this file to config.yml after filling in your own details.

version: 0.0.6
api_type: X-Plane
api_key: <api_key>
api_host: "adsbx-flight-sim-traffic.p.rapidapi.com"
source_ac_db_path: assets/aircraft-database-complete-2022-09.csv
lat: <decimal lat>
lon: <decimal lon>
criteria: all # mil, civil, or all
max_distance: 10 # 1-25nm
min_altitude: 100
max_altitude: 12000
do_not_repeat_for: 240 # seconds. After they are first announced, airframes often appear in subsequent API calls. What is the minimum amount of time that should pass until the same airframe is announced a second time?